### ISSUE TITLE
Patch area at $3A84

### ISSUE THREAD

**Issue by TommyGH** [Michaelangel007/apple2_dos33#1]
As an fyi, after 3A81: you have the following:

=== DOS 3.3 D? PATCH ===        
                    3A84:AD BD 35   LDA $35BD ; TODO
                    3A87:8D E6 35   STA $35E6 ; TODO
                    3A8A:8D EA 35   STA $35EA ; TODO
                    3A8D:BA         TSX             
                    3A8E:8E 9B 33   STX $339B ; TODO
                    3A91:4C 7F 33   JMP $337F ; TODO
=== DOS 3.3 ? PATCH ===        

"Beneath Apple Dos (Updated for Apple IIe)" on p.  8-41 has this description:

"BA84-BA93 Patch called from $B683.
 Set file manager parameters, byte offset, and
 record number to zero.  Save stack in stack
register save area.
Exit through $B37F (exit file manager)."

This code is in Apple Dos 3.3 (1983).

**Comment by Michaelangel007** [comment]
Thanks Tommy.  This has been fixed now.

```
                        ; === DOS 3.3 D PATCH ===       Called from GOBACK+5 = $3683
3A84:AD BD 35                       LDA CCBBYT                                      
3A87:8D E6 35                       STA DCBCSB                                      
3A8A:8D EA 35                       STA DCBCRR                                      
3A8D:BA                             TSX                                             
3A8E:8E 9B 33                       STX ENTSTK                                      
3A91:4C 7F 33                       JMP GOODIO                                      
                        ; === DOS 3.3 D PATCH ===                                   
```

and

```
3683:4C 46 25       121             JMP FIXIT2      ;Go to FIXIT2 as exit           ; Oh look, we have lowercase CapsLock on //e!
                        ; === DOS 3.3 D PATCH ===                                   
3683:4C 84 3A       121             JMP FIXIT3                                      ; DOS 3.3 1983
                        ; === DOS 3.3 D PATCH ===                                   
```
