### ISSUE TITLE
Discovery:  Why is 1E70 a JMP MONBRK instruction since Monitor only examines the address field.

### ISSUE THREAD

**Issue by TommyGH** [Michaelangel007/apple2_dos33#11]
Here is an interesting discovery that took me a long time to figure out today, so I thought I'd share it with you.  There are no issues with apple2_dos33, other than you might want to somehow explain this in your work.

In the IFB table at $1E51 are a bunch of JMP instructions that get copied to $3D0.  At $1E6E and $1E6F are NOP (unused) bytes, followed by:

1E70:4C 59 FA  220 JMP MONBRK   ; $3EF: JMP $FA59 Autostart BRK handler

This JMP at 1E70 ends up at $3EF.

I noticed while working with a DiversiDos disk that the byte at $3EF was clobbered with a JMP instruction that started where the 2 NOPs were.  So DiversiDos ended up with:

$3ED:  4C DF BC  JMP $BCDF
$3F0:  59 FA

So the "instruction" part of the OP code for the JMP MONBRK turned into a LDY instruction ("BC").

I thought "How could BRK be handled properly on DiversiDos?"

The answer is simple.  In the autostart Monitor ROM is:

FA65:  6C F0 03  JMP (BRKV)

The Monitor does not care about the op code at $03EF, only the address at $03F0.

Ok, next question.  "Can I always get rid of the #$4C at $3EF and use $3EF however I like?"

The hint is in the original source code on the JMP MONBRK line:

"(JMP IS FOR PROP RELOC)".

The #$4C is needed so that the relocation code during a MASTER disk boot will work properly by getting the 3 byte instruction and then examining the address to see if it needs to be altered.

The end.

**Comment by TommyGH** [comment]
There is a related issue with the following code snippet:

1E6E:EA             218             NOP                                             ; [.. wastes 2 bytes -- NEVER used anywhere
1E6F:EA             219             NOP                                             ;  ..]

I know you wrote "NEVER" used (and they aren't), but there are 2 purposes for these 2 NOPs here.
1. They fill the 2 bytes at $3ED and $3EE when the IFB table is copied to $3D0..$3FF
2. They need to be something like NOP to align the following instructions for examination during the MASTER disk "relocate" code.

**Comment by Michaelangel007** [comment]
Thanks for the info Tommy !

Ah, yes, the JMP is for run-time relocation (pseudo linker) sounds like I need to comment on that.  Thanks for doing the "leg-work."

**Comment by Michaelangel007** [comment]
Finally got around to fixing this.  Added your insight and added your attribution.
