### ISSUE TITLE
INPRT and INPORT

### ISSUE THREAD

**Issue by TommyGH** [Michaelangel007/apple2_dos33#7]
The monitor source listing defines 2 symbols:
  FE8B  INPORT
  FE8D  INPRT

The DOS3.3 source listing defines 1 symbol:
  FE8B  INPRT

Nothing wrong in this repository.  
Just pointing out that a snarky comment on the line defining INPRT should probably be made.

**Comment by Michaelangel007** [comment]
I like the way you think. :-)

Snarky commentary added to line:

```
00090 054 INPRT       EQU $FE8B       ; SET IN PORT
```
